# aimap configuration file
# Copy this file to .aimap.yml and customize for your project

# Source directory for rule files
source: .rules

# Agents to build for
# This example enables only `agents` and `claude` by default.
# Available: agents, claude, cline, roocode, cursor, windsurf,
#            copilot, amazonq, aider, jetbrains, gemini
agents:
  - agents      # Universal (AGENTS.md with all rules)
  - claude      # Claude (CLAUDE.md with list of @ references)

# Custom output paths (optional)
# outputs:
#   claude: CUSTOM_CLAUDE.md
#   cline: .custom-clinerules
#   copilot: .github/custom-copilot.md
